kind: ArgoComposer

kubernetes:
    version: latest

argo-cd:
    version: latest

presets:
    source: https://github.com/codemask-labs/argo-composer-presets
    reference: v1.0.0

options:
    use-application-overlays: false
    use-application-per-project: true
