apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data-engineering
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "https://github.com/codemask-labs/argocd-resources.git"
  destinations:
    - namespace: "*"
      server: "*"
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-engineering
  namespace: argocd
spec:
  project: data-engineering
  source:
    repoURL: https://github.com/codemask-labs/argocd-resources.git
    targetRevision: HEAD
    path: ./projects/data-engineering/apps
