---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    <% if(useImageAutoUpdater) { %>argocd-image-updater.argoproj.io/image-list: i=<%= imageURL %>
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: "kustomization:./"
    argocd-image-updater.argoproj.io/i.update-strategy: latest
    argocd-image-updater.argoproj.io/i.allow-tags: regexp:main-*
    argocd-image-updater.argoproj.io/i.force-update: "true"<% } %>
#    argocd-image-updater.argoproj.io/i.pull-secret: pullsecret:argocd/regcred
  name: <%= appName %>-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: <%= projectName %>
  source:
    repoURL: <%= mainRepoURL %>
    targetRevision: main
    path: ./projects/<%= projectName %>/apps/<%= appName %>/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: <%= appName %>-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - CreateNamespace=true
    retry:
      limit: 3 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
  revisionHistoryLimit: 0
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
  name: <%= appName %>-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: <%= projectName %>
  source:
    repoURL: <%= mainRepoURL %>
    targetRevision: main
    path: ./projects/<%= projectName %>/apps/<%= appName %>/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: <%= appName %>-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - CreateNamespace=true
    retry:
      limit: 3 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
  revisionHistoryLimit: 0
---
