apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: <%= addonsProjectName %>
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-image-updater
  source:
    chart: argocd-image-updater
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 0.9.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 0
