apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: ${{ project.name }}
  namespace: argocd
spec:
  sourceRepos:
    - ${{ inputs.repository-url }}
  destinations:
    - server: "*"
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
