apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: example
  namespace: argocd
spec:
  sourceRepos:
  - https://github.com/example/argocd-resources
  destinations:
  - server: '*'
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
