apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "<%= projectName %>"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project
  sourceRepos:
    - "<%= mainRepoURL %>"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
