apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "<%= projectName %>"
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "<%= mainRepoURL %>"
  destinations:
    - namespace: "*"
      server: "*"
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
